### ISSUE TITLE
API support

### ISSUE THREAD

**Issue by vynt-kenshiro** [RNT-Forest/OVZCP#4]
Hello,

Do you implement the API?

**Comment by rnt-maple** [comment]
Hi vynt-kenshiro, 

Which API do you mean? At low level there are prlctl commands executed to configure openvz. We call those bundled commands "Jobs" and they're located in another repository (https://github.com/RNT-Forest/OVZ)

**Comment by rnt-maple** [comment]
No we do not support the API of WHMCS, sorry. I assume you talk about this API http://developers.whmcs.com/api/ 

In this case it would be the other way round, so that the API of WHMCS would be called from code in OVZCP. But neither WHMCS would call an API on OVZCP nor OVZCP would call an API on WHMCS at the moment. 

 Our focus is on the technical management of OpenVZ7 hostservers.
